version: '3.8'

services:
  # https://vinybrasil.github.io/portfolio/kafkafastapiasync/
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - ${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}
    networks:
      - zookeeper-kafka

  # https://vinybrasil.github.io/portfolio/kafkafastapiasync/
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - zookeeper-kafka

  backend:
    build: ./backend
    command: uvicorn api.server:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/code
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - kafka
    networks:
      - backend-frontend
      - zookeeper-kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # Windows bug with WSL 2: https://github.com/microsoft/WSL/issues/4739#issue-534049240
    # ==========
    environment:
      - WATCHPACK_POLLING=true
    # ==========
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /usr/src/app/node_modules
    networks:
      - backend-frontend
    tty: true
    stdin_open: true
    depends_on:
      - backend

  auth:
    build:
      context: ./auth-frontend
      dockerfile: Dockerfile.dev
    # Windows bug with WSL 2: https://github.com/microsoft/WSL/issues/4739#issue-534049240
    # ==========
    environment:
      - WATCHPACK_POLLING=true
    # ==========
    ports:
      - 3340:3340
    volumes:
      - ./auth-frontend:/app
      - /app/node_modules
    networks:
      - frontend-services
    stdin_open: true

  task-checker:
    build: ./TaskChecker
    command: python3 main.py
    volumes:
      - ./TaskChecker:/code
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    privileged: true
    depends_on:
      - kafka
    networks:
      - zookeeper-kafka
    stdin_open: true

  chat:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile.dev
    # Windows bug with WSL 2: https://github.com/microsoft/WSL/issues/4739#issue-534049240
    # ==========
    environment:
      - WATCHPACK_POLLING=true
    # ==========
    ports:
      - 3341:3341
    volumes:
      - ./chat-frontend:/app
      - /app/node_modules
    networks:
      - frontend-services
    stdin_open: true

networks:
  backend-frontend:
  zookeeper-kafka:
  frontend-services:

