version: '3.8'

services:
  postgres-db:
    image: postgres
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_HOST=${DB_HOST}
    volumes:  
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-backend
      - backend-frontend
      
  backend:
    build: ./backend
    command: uvicorn api.server:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/code
    env_file:
      - .env
    environment:
      - DEBUG=1
    ports:
      - "${BACKEND_PORT}:8000"
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - db-backend
      - redis-go-net
      - rabbitmq-go-net
      
  frontend:
    build: ./frontend
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - backend-frontend
    command: npm start
    tty: true
    stdin_open: true
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - d:/Volumes/TCS/rabbitmq/data:/var/lib/rabbitmq
      - d:/Volumes/TCS/rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq-go-net
      
  redis:
    image: redis:7.0.4-alpine
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - D:\Volumes\TCS\redis:/data
    networks:
      - redis-go-net
      
  celery-worker:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - postgres-db
    volumes:
      - ./backend:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: "celery -A celery_worker.worker worker -l info -Q check-solution-queue -c 1"
    networks:
      - rabbitmq-go-net
      - redis-go-net
      - db-backend
    
  celery-flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq-go-net
      - redis-go-net
    
    
    
    
networks:
  db-backend:
  backend-frontend:
  rabbitmq-go-net:
  redis-go-net:
  
volumes:
    pgdata: