version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn api.server:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/code
    env_file:
      - .env
    environment:
      - DEBUG=1
    ports:
      - "${BACKEND_PORT}:8000"
    restart: on-failure
    networks:
      - redis-go-net
      - rabbitmq-go-net
      - backend-frontend

  rabbitmq:
    image: rabbitmq:3.5
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - D:/Volumes/TCS/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - D:/Volumes/TCS/rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq-go-net

  redis:
    image: redis:7.0.4-alpine
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - D:/Volumes/TCS/redis:/data
    networks:
      - redis-go-net

  celery-worker:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./backend:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: "celery -A celery_worker.worker worker -l info -Q check-solution-queue -c 1"
    networks:
      - rabbitmq-go-net
      - redis-go-net

  celery-flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq-go-net
      - redis-go-net




networks:
  backend-frontend:
  rabbitmq-go-net:
  redis-go-net:

