version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn api.server:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/code
    env_file:
      - .env
    environment:
      - DEBUG=1
    ports:
      - "${BACKEND_PORT}:8000"
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - redis-go-net
      - rabbitmq-go-net
      - backend-frontend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - REACT_APP_PROD_SITE_URL=${REACT_APP_PROD_SITE_URL}
      - REACT_APP_DEV_SITE_URL=${REACT_APP_DEV_SITE_URL}
      - REACT_APP_PROD_API_URL=${REACT_APP_PROD_API_URL}
      - REACT_APP_DEV_API_URL=${REACT_APP_DEV_API_URL}
      - REACT_APP_PROD_VK_CLIENT_ID=${REACT_APP_PROD_VK_CLIENT_ID}
      - REACT_APP_DEV_VK_CLIENT_ID=${REACT_APP_DEV_VK_CLIENT_ID}
      - REACT_APP_SECRET=${REACT_APP_SECRET}
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - backend-frontend
    tty: true
    stdin_open: true

  rabbitmq:
    image: rabbitmq:3.11-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_PORT_ADD}:15672
    volumes:
      - ~/Volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ~/Volumes/rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq-go-net

  redis:
    image: redis:7.0.4-alpine
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ~/Volumes/redis:/data
    networks:
      - redis-go-net

  celery-worker:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./backend:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: "celery -A celery_worker.worker worker -l info -Q check-solution-queue -c 1"
    networks:
      - rabbitmq-go-net
      - redis-go-net

  celery-flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq-go-net
      - redis-go-net




networks:
  backend-frontend:
  rabbitmq-go-net:
  redis-go-net:

