from .user import router as user_router
from .auth import router as auth_router
from .group import router as group_router
from .course import router as course_router
from .task import router as task_router
from .lesson import router as lesson_router
from .solution import router as solution_router
from .admin import router as admin_router
from .chat_message import router as chat_message_router
from .stat import router as stat_router
from .test import router as test_router
from .lessons_tasks import router as lessons_tasks_router
from .courses_lessons import router as courses_lessons_router
from .groups_courses import router as groups_courses_router
