"""add admin

Revision ID: 0123e56a6865
Revises: 5886c44829f2
Create Date: 2021-04-25 22:04:37.932822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0123e56a6865'
down_revision = '5886c44829f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'middle_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('user', 'middle_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
