"""add group name

Revision ID: 0b4a507ed621
Revises: ecf58818fa8f
Create Date: 2021-05-22 01:05:41.235874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4a507ed621'
down_revision = 'ecf58818fa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_group', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_group', 'name')
    # ### end Alembic commands ###
