"""add roles and statuses to user

Revision ID: 0fa33261a09d
Revises: 613ef72caece
Create Date: 2021-04-19 18:01:01.330812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa33261a09d'
down_revision = '613ef72caece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
