"""rework connection user_task_grop_course

Revision ID: 156de7f5f51b
Revises: ea3281d11af8
Create Date: 2022-02-21 17:25:57.172391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156de7f5f51b'
down_revision = 'ea3281d11af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_tasks_courses_groups',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['dbo_group.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id', 'course_id', 'group_id')
    )
    op.drop_table('dbo_users_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_tasks',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], name='dbo_users_tasks_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], name='dbo_users_tasks_user_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name='dbo_users_tasks_pkey')
    )
    op.drop_table('dbo_users_tasks_courses_groups')
    # ### end Alembic commands ###
