"""delete admin

Revision ID: 2a4e0d8facb6
Revises: a3fe1b11969f
Create Date: 2021-04-25 22:23:29.340481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4e0d8facb6'
down_revision = 'a3fe1b11969f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_admin_user_id_user_id'),
    sa.PrimaryKeyConstraint('id', name='admin_pkey')
    )
    # ### end Alembic commands ###
