"""empty message

Revision ID: 2c7495349291
Revises: f400359725ab
Create Date: 2022-10-06 08:09:46.404006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c7495349291'
down_revision = 'f400359725ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_lessons_tasks', sa.Column('task_type', sa.Enum('CLASS_WORK', 'HOME_WORK', 'ADDITIONAL_WORK', name='tasktype'), nullable=True))
    op.drop_column('dbo_task', 'task_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_task', sa.Column('task_type', postgresql.ENUM('CLASS_WORK', 'HOME_WORK', 'ADDITIONAL_WORK', name='tasktype'), autoincrement=False, nullable=True))
    op.drop_column('dbo_lessons_tasks', 'task_type')
    # ### end Alembic commands ###
