"""db update

Revision ID: 3284c7e8a49b
Revises: a26f13a43ee8
Create Date: 2021-05-21 22:46:34.311318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3284c7e8a49b'
down_revision = 'a26f13a43ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_courses_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['dbo_course.id'], name='fk_dbo_courses_groups_dbo_course_course_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group'], ['dbo_group.id'], name='fk_dbo_courses_groups_dbo_group_group_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_users_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['dbo_group.id'], name='fk_dbo_users_groups_dbo_group_group_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_users_groups_dbo_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dbo_users_tasks')
    op.drop_table('dbo_users_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_course_role', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course'], ['dbo_course.id'], name='fk_dbo_users_courses_dbo_course_course_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_users_courses_dbo_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dbo_users_courses_pkey')
    )
    op.create_table('dbo_users_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_task_role', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task'], ['dbo_task.id'], name='fk_dbo_users_tasks_dbo_task_task_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_users_tasks_dbo_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dbo_users_tasks_pkey')
    )
    op.drop_table('dbo_users_groups')
    op.drop_table('dbo_courses_groups')
    op.drop_table('dbo_group')
    # ### end Alembic commands ###
