"""empty message

Revision ID: 33d8d686b42e
Revises: e5fe1d8b0db1
Create Date: 2023-02-13 18:00:21.031834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d8d686b42e'
down_revision = 'e5fe1d8b0db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa_enum = sa.Enum('PYTHON_IO', 'PYTHON_UT', name='testtype')
    sa_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('dbo_solution', sa.Column('test_type', sa.Enum('PYTHON_IO', 'PYTHON_UT', name='testtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_solution', 'test_type')
    sa_enum = sa.Enum(name='testtype')
    sa_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
