"""init database

Revision ID: 44e77fe97e28
Revises: 
Create Date: 2021-05-01 22:38:22.211988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e77fe97e28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('vk_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_lessons_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], name='fk_dbo_lessons_courses_dbo_course_course_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['dbo_lesson.id'], name='fk_dbo_lessons_courses_dbo_lesson_lesson_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_lessons_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['dbo_lesson.id'], name='fk_dbo_lessons_tasks_dbo_lesson_lesson_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], name='fk_dbo_lessons_tasks_dbo_task_task_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_users_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_course_role', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], name='fk_dbo_users_courses_dbo_course_course_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], name='fk_dbo_users_courses_dbo_user_user_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_users_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], name='fk_dbo_users_tasks_dbo_task_task_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], name='fk_dbo_users_tasks_dbo_user_user_id_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_users_tasks')
    op.drop_table('dbo_users_courses')
    op.drop_table('dbo_lessons_tasks')
    op.drop_table('dbo_lessons_courses')
    op.drop_table('dbo_user')
    op.drop_table('dbo_task')
    op.drop_table('dbo_lesson')
    op.drop_table('dbo_course')
    # ### end Alembic commands ###
