"""add solutions

Revision ID: 596cf1f4a230
Revises: 3284c7e8a49b
Create Date: 2021-05-22 00:20:53.629964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596cf1f4a230'
down_revision = '3284c7e8a49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dbo_users_groups_dbo_user_user_id', 'dbo_users_groups', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_groups_dbo_group_group_id', 'dbo_users_groups', type_='foreignkey')
    op.drop_column('dbo_users_groups', 'user')
    op.drop_column('dbo_users_groups', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_users_groups', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_users_groups', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_dbo_users_groups_dbo_group_group_id', 'dbo_users_groups', 'dbo_group', ['group'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_groups_dbo_user_user_id', 'dbo_users_groups', 'dbo_user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
