"""edit user task conection

Revision ID: 601e6cf26674
Revises: 663cfb95119c
Create Date: 2021-07-02 13:48:03.905542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601e6cf26674'
down_revision = '663cfb95119c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dbo_solution_dbo_users_courses_tasks_id_user_course_task', 'dbo_solution', type_='foreignkey')
    op.create_foreign_key('fk_dbo_solution_dbo_users_courses_tasks_id_user_course_task', 'dbo_solution', 'dbo_users_courses_tasks', ['user_course_task'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_dbo_users_courses_tasks_dbo_course_id_course', 'dbo_users_courses_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_tasks_dbo_user_id_user', 'dbo_users_courses_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_tasks_dbo_task_id_task', 'dbo_users_courses_tasks', type_='foreignkey')
    op.create_foreign_key('fk_dbo_users_courses_tasks_dbo_task_id_task', 'dbo_users_courses_tasks', 'dbo_task', ['task'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_courses_tasks_dbo_course_id_course', 'dbo_users_courses_tasks', 'dbo_course', ['course'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_courses_tasks_dbo_user_id_user', 'dbo_users_courses_tasks', 'dbo_user', ['user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dbo_users_courses_tasks_dbo_user_id_user', 'dbo_users_courses_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_tasks_dbo_course_id_course', 'dbo_users_courses_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_tasks_dbo_task_id_task', 'dbo_users_courses_tasks', type_='foreignkey')
    op.create_foreign_key('fk_dbo_users_courses_tasks_dbo_task_id_task', 'dbo_users_courses_tasks', 'dbo_task', ['task'], ['id'])
    op.create_foreign_key('fk_dbo_users_courses_tasks_dbo_user_id_user', 'dbo_users_courses_tasks', 'dbo_user', ['user'], ['id'])
    op.create_foreign_key('fk_dbo_users_courses_tasks_dbo_course_id_course', 'dbo_users_courses_tasks', 'dbo_course', ['course'], ['id'])
    op.drop_constraint('fk_dbo_solution_dbo_users_courses_tasks_id_user_course_task', 'dbo_solution', type_='foreignkey')
    op.create_foreign_key('fk_dbo_solution_dbo_users_courses_tasks_id_user_course_task', 'dbo_solution', 'dbo_users_courses_tasks', ['user_course_task'], ['id'])
    # ### end Alembic commands ###
