"""update user model

Revision ID: 6632724d1fe4
Revises: 2a4e0d8facb6
Create Date: 2021-05-01 17:50:12.513228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6632724d1fe4'
down_revision = '2a4e0d8facb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'jwt_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('jwt_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
