"""add group_user

Revision ID: 6b53f19d1950
Revises: 79e62ecf89bc
Create Date: 2021-05-22 00:52:06.769425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b53f19d1950'
down_revision = '79e62ecf89bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_task', sa.Column('max_score', sa.Float(), nullable=True))
    op.add_column('dbo_users_courses_tasks', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('dbo_users_groups', sa.Column('user_group_role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_users_groups', 'user_group_role')
    op.drop_column('dbo_users_courses_tasks', 'score')
    op.drop_column('dbo_task', 'max_score')
    # ### end Alembic commands ###
