"""rename some fields

Revision ID: 6f3e016030e9
Revises: 44e77fe97e28
Create Date: 2021-05-02 00:17:07.952044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3e016030e9'
down_revision = '44e77fe97e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_lessons_courses', sa.Column('course', sa.Integer(), nullable=True))
    op.add_column('dbo_lessons_courses', sa.Column('lesson', sa.Integer(), nullable=True))
    op.drop_constraint('fk_dbo_lessons_courses_dbo_course_course_id_id', 'dbo_lessons_courses', type_='foreignkey')
    op.drop_constraint('fk_dbo_lessons_courses_dbo_lesson_lesson_id_id', 'dbo_lessons_courses', type_='foreignkey')
    op.create_foreign_key('fk_dbo_lessons_courses_dbo_lesson_lesson_id', 'dbo_lessons_courses', 'dbo_lesson', ['lesson'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_lessons_courses_dbo_course_course_id', 'dbo_lessons_courses', 'dbo_course', ['course'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_lessons_courses', 'lesson_id')
    op.drop_column('dbo_lessons_courses', 'course_id')
    op.add_column('dbo_lessons_tasks', sa.Column('lesson', sa.Integer(), nullable=True))
    op.add_column('dbo_lessons_tasks', sa.Column('task', sa.Integer(), nullable=True))
    op.drop_constraint('fk_dbo_lessons_tasks_dbo_task_task_id_id', 'dbo_lessons_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_lessons_tasks_dbo_lesson_lesson_id_id', 'dbo_lessons_tasks', type_='foreignkey')
    op.create_foreign_key('fk_dbo_lessons_tasks_dbo_task_task_id', 'dbo_lessons_tasks', 'dbo_task', ['task'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_lessons_tasks_dbo_lesson_lesson_id', 'dbo_lessons_tasks', 'dbo_lesson', ['lesson'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_lessons_tasks', 'lesson_id')
    op.drop_column('dbo_lessons_tasks', 'task_id')
    op.add_column('dbo_users_courses', sa.Column('course', sa.Integer(), nullable=True))
    op.add_column('dbo_users_courses', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('fk_dbo_users_courses_dbo_course_course_id_id', 'dbo_users_courses', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_dbo_user_user_id_id', 'dbo_users_courses', type_='foreignkey')
    op.create_foreign_key('fk_dbo_users_courses_dbo_user_user_id', 'dbo_users_courses', 'dbo_user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_courses_dbo_course_course_id', 'dbo_users_courses', 'dbo_course', ['course'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_users_courses', 'user_id')
    op.drop_column('dbo_users_courses', 'course_id')
    op.add_column('dbo_users_tasks', sa.Column('task', sa.Integer(), nullable=True))
    op.add_column('dbo_users_tasks', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('fk_dbo_users_tasks_dbo_user_user_id_id', 'dbo_users_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_tasks_dbo_task_task_id_id', 'dbo_users_tasks', type_='foreignkey')
    op.create_foreign_key('fk_dbo_users_tasks_dbo_user_user_id', 'dbo_users_tasks', 'dbo_user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_tasks_dbo_task_task_id', 'dbo_users_tasks', 'dbo_task', ['task'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_users_tasks', 'user_id')
    op.drop_column('dbo_users_tasks', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_users_tasks', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_users_tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_dbo_users_tasks_dbo_task_task_id', 'dbo_users_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_tasks_dbo_user_user_id', 'dbo_users_tasks', type_='foreignkey')
    op.create_foreign_key('fk_dbo_users_tasks_dbo_task_task_id_id', 'dbo_users_tasks', 'dbo_task', ['task_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_tasks_dbo_user_user_id_id', 'dbo_users_tasks', 'dbo_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_users_tasks', 'user')
    op.drop_column('dbo_users_tasks', 'task')
    op.add_column('dbo_users_courses', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_users_courses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_dbo_users_courses_dbo_course_course_id', 'dbo_users_courses', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_dbo_user_user_id', 'dbo_users_courses', type_='foreignkey')
    op.create_foreign_key('fk_dbo_users_courses_dbo_user_user_id_id', 'dbo_users_courses', 'dbo_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_courses_dbo_course_course_id_id', 'dbo_users_courses', 'dbo_course', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_users_courses', 'user')
    op.drop_column('dbo_users_courses', 'course')
    op.add_column('dbo_lessons_tasks', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_lessons_tasks', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_dbo_lessons_tasks_dbo_lesson_lesson_id', 'dbo_lessons_tasks', type_='foreignkey')
    op.drop_constraint('fk_dbo_lessons_tasks_dbo_task_task_id', 'dbo_lessons_tasks', type_='foreignkey')
    op.create_foreign_key('fk_dbo_lessons_tasks_dbo_lesson_lesson_id_id', 'dbo_lessons_tasks', 'dbo_lesson', ['lesson_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_lessons_tasks_dbo_task_task_id_id', 'dbo_lessons_tasks', 'dbo_task', ['task_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_lessons_tasks', 'task')
    op.drop_column('dbo_lessons_tasks', 'lesson')
    op.add_column('dbo_lessons_courses', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_lessons_courses', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_dbo_lessons_courses_dbo_course_course_id', 'dbo_lessons_courses', type_='foreignkey')
    op.drop_constraint('fk_dbo_lessons_courses_dbo_lesson_lesson_id', 'dbo_lessons_courses', type_='foreignkey')
    op.create_foreign_key('fk_dbo_lessons_courses_dbo_lesson_lesson_id_id', 'dbo_lessons_courses', 'dbo_lesson', ['lesson_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_lessons_courses_dbo_course_course_id_id', 'dbo_lessons_courses', 'dbo_course', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('dbo_lessons_courses', 'lesson')
    op.drop_column('dbo_lessons_courses', 'course')
    # ### end Alembic commands ###
