"""empty message

Revision ID: 748f4d5c72eb
Revises: 2c7495349291
Create Date: 2022-11-04 08:14:41.754495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748f4d5c72eb'
down_revision = '2c7495349291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbo_user', 'vk_access_token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbo_user', 'vk_access_token',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
