"""add group_user

Revision ID: 79e62ecf89bc
Revises: acc286a82cd4
Create Date: 2021-05-22 00:24:07.492815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e62ecf89bc'
down_revision = 'acc286a82cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_users_groups', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('dbo_users_groups', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_dbo_users_groups_dbo_group_group_id', 'dbo_users_groups', 'dbo_group', ['group'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_groups_dbo_user_user_id', 'dbo_users_groups', 'dbo_user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dbo_users_groups_dbo_user_user_id', 'dbo_users_groups', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_groups_dbo_group_group_id', 'dbo_users_groups', type_='foreignkey')
    op.drop_column('dbo_users_groups', 'user')
    op.drop_column('dbo_users_groups', 'group')
    # ### end Alembic commands ###
