"""add field status to users_tasks

Revision ID: 7b3e04d02a1d
Revises: 6f3e016030e9
Create Date: 2021-05-02 02:02:55.476395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3e04d02a1d'
down_revision = '6f3e016030e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_users_tasks', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_users_tasks', 'status')
    # ### end Alembic commands ###
