"""empty message

Revision ID: a14d949a31f6
Revises: 
Create Date: 2022-07-25 19:58:30.546125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a14d949a31f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_image',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_lesson',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('task_type', sa.Enum('CLASS_WORK', 'HOME_WORK', 'ADDITIONAL_WORK', name='tasktype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('vk_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'UNDEFINED', name='userstatus'), nullable=True),
    sa.Column('vk_access_token', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.String(length=2000), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], ),
    sa.ForeignKeyConstraint(['from_id'], ['dbo_user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['dbo_group.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_courses_lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('queue_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['dbo_lesson.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'course_id')
    )
    op.create_table('dbo_groups_courses',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['dbo_group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'course_id')
    )
    op.create_table('dbo_lessons_tasks',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['dbo_lesson.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'task_id')
    )
    op.create_table('dbo_refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_solution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ERROR', 'ON_REVIEW', 'COMPLETE_NOT_MAX', 'COMPLETE', name='solutionstatus'), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_finish', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['dbo_course.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['dbo_group.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'OWNER', name='usergrouprole'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['dbo_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dbo_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_users_groups')
    op.drop_table('dbo_teacher')
    op.drop_table('dbo_solution')
    op.drop_table('dbo_refresh_token')
    op.drop_table('dbo_lessons_tasks')
    op.drop_table('dbo_groups_courses')
    op.drop_table('dbo_courses_lessons')
    op.drop_table('dbo_chat_message')
    op.drop_table('dbo_admin')
    op.drop_table('dbo_user')
    op.drop_table('dbo_task')
    op.drop_table('dbo_lesson')
    op.drop_table('dbo_image')
    op.drop_table('dbo_group')
    op.drop_table('dbo_course')
    # ### end Alembic commands ###
