"""update user tokens v.3 

Revision ID: a26f13a43ee8
Revises: b076a5c46c3c
Create Date: 2021-05-21 19:25:47.955517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26f13a43ee8'
down_revision = 'b076a5c46c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_refresh_token_dbo_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_refresh_token')
    # ### end Alembic commands ###
