"""add solutions 2

Revision ID: acc286a82cd4
Revises: 596cf1f4a230
Create Date: 2021-05-22 00:22:25.835375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc286a82cd4'
down_revision = '596cf1f4a230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_courses_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['dbo_course.id'], name='fk_dbo_users_courses_tasks_dbo_course_id_course'),
    sa.ForeignKeyConstraint(['task'], ['dbo_task.id'], name='fk_dbo_users_courses_tasks_dbo_task_id_task'),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_users_courses_tasks_dbo_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dbo_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_course_task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_course_task'], ['dbo_users_courses_tasks.id'], name='fk_dbo_solution_dbo_users_courses_tasks_id_user_course_task'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_solution')
    op.drop_table('dbo_users_courses_tasks')
    # ### end Alembic commands ###
