"""edit course

Revision ID: ad80a39a829c
Revises: 7b3e04d02a1d
Create Date: 2021-05-21 15:28:09.021646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad80a39a829c'
down_revision = '7b3e04d02a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_course', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('dbo_users_tasks', sa.Column('user_task_role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_users_tasks', 'user_task_role')
    op.drop_column('dbo_course', 'description')
    # ### end Alembic commands ###
