"""add jwt and access token user

Revision ID: ad9ee8649b3f
Revises: 
Create Date: 2021-04-23 22:27:04.508845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9ee8649b3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('jwt_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'jwt_token')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
