"""update user tokens v.2

Revision ID: b076a5c46c3c
Revises: fcedd6e6140f
Create Date: 2021-05-21 19:24:49.728780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b076a5c46c3c'
down_revision = 'fcedd6e6140f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_user', 'refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_user', sa.Column('refresh_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
