"""empty message

Revision ID: b4db414fdcad
Revises: a14d949a31f6
Create Date: 2022-08-04 13:32:52.078673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4db414fdcad'
down_revision = 'a14d949a31f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_task_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.String(), nullable=False),
    sa.Column('output_data', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dbo_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_task_test')
    # ### end Alembic commands ###
