"""add user-course connection

Revision ID: bf7ac7601bb9
Revises: ef7d8aa931e8
Create Date: 2021-07-02 17:00:11.480165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7ac7601bb9'
down_revision = 'ef7d8aa931e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_course_role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_users_courses')
    # ### end Alembic commands ###
