"""edit user task conection: delete conection

Revision ID: c4c90943ab2d
Revises: e9c3dd3cf37a
Create Date: 2021-07-02 14:09:09.427961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4c90943ab2d'
down_revision = 'e9c3dd3cf37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['dbo_task.id'], name='fk_dbo_users_tasks_dbo_task_id_task', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_users_tasks_dbo_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dbo_solution')
    op.drop_table('dbo_users_courses_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_users_courses_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task'], ['dbo_task.id'], name='fk_dbo_users_courses_tasks_dbo_task_id_task', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_users_courses_tasks_dbo_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dbo_users_courses_tasks_pkey')
    )
    op.create_table('dbo_solution',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_course_task', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_course_task'], ['dbo_users_courses_tasks.id'],
                                            name='fk_dbo_solution_dbo_users_courses_tasks_id_user_course_task',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='dbo_solution_pkey')
                    )
    op.drop_table('dbo_users_tasks')
    # ### end Alembic commands ###
