"""connect solution with utcg

Revision ID: c58fbdb18b00
Revises: 7f7f05befd44
Create Date: 2022-02-21 18:34:48.368093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58fbdb18b00'
down_revision = '7f7f05befd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_solution', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('dbo_solution', sa.Column('task_id', sa.Integer(), nullable=False))
    op.add_column('dbo_solution', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('dbo_solution', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key('dbo_solution_fkey', 'dbo_solution', 'dbo_users_tasks_courses_groups', ['user_id', 'task_id', 'course_id', 'group_id'], ['user_id', 'task_id', 'course_id', 'group_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dbo_solution_fkey', 'dbo_solution', type_='foreignkey')
    op.drop_column('dbo_solution', 'group_id')
    op.drop_column('dbo_solution', 'course_id')
    op.drop_column('dbo_solution', 'task_id')
    op.drop_column('dbo_solution', 'user_id')
    # ### end Alembic commands ###
