"""fix connection user-task

Revision ID: e1a78d806aa9
Revises: fd1d27ed83ec
Create Date: 2021-07-02 17:42:18.107016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a78d806aa9'
down_revision = 'fd1d27ed83ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_users_courses', sa.Column('course', sa.Integer(), nullable=True))
    op.add_column('dbo_users_courses', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_dbo_users_courses_dbo_course_course_id', 'dbo_users_courses', 'dbo_course', ['course'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_dbo_users_courses_dbo_user_user_id', 'dbo_users_courses', 'dbo_user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dbo_users_courses_dbo_user_user_id', 'dbo_users_courses', type_='foreignkey')
    op.drop_constraint('fk_dbo_users_courses_dbo_course_course_id', 'dbo_users_courses', type_='foreignkey')
    op.drop_column('dbo_users_courses', 'user')
    op.drop_column('dbo_users_courses', 'course')
    # ### end Alembic commands ###
