"""empty message

Revision ID: e1b6c762bb50
Revises: b4db414fdcad
Create Date: 2022-08-04 13:36:19.558132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b6c762bb50'
down_revision = 'b4db414fdcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbo_task_test', 'input_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dbo_task_test', 'output_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbo_task_test', 'output_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dbo_task_test', 'input_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
