"""add admin

Revision ID: e5bdd0d0a853
Revises: ad80a39a829c
Create Date: 2021-05-21 16:03:38.738710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bdd0d0a853'
down_revision = 'ad80a39a829c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['dbo_user.id'], name='fk_dbo_admin_dbo_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('dbo_user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('dbo_admin')
    # ### end Alembic commands ###
