"""add DockerRunImage entity

Revision ID: e5fe1d8b0db1
Revises: 748f4d5c72eb
Create Date: 2022-12-18 19:02:20.858230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fe1d8b0db1'
down_revision = '748f4d5c72eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_docker_run_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signature', sa.String(length=40), nullable=True),
    sa.Column('docker_image', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    op.create_table('dbo_solutions_docker_run_images',
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('docker_run_image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docker_run_image_id'], ['dbo_docker_run_image.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['dbo_solution.id'], ),
    sa.PrimaryKeyConstraint('solution_id', 'docker_run_image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_solutions_docker_run_images')
    op.drop_table('dbo_docker_run_image')
    # ### end Alembic commands ###
