"""update task.description length string

Revision ID: ea3281d11af8
Revises: 0507110ccfa2
Create Date: 2022-02-18 01:33:20.835465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3281d11af8'
down_revision = '0507110ccfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbo_task', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=4000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbo_task', 'description',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
