"""delete field solution.name

Revision ID: eb14f9f7c383
Revises: c58fbdb18b00
Create Date: 2022-02-21 18:44:55.686768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb14f9f7c383'
down_revision = 'c58fbdb18b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_solution', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_solution', sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
