"""empty message

Revision ID: f32f10b5df1e
Revises: 33d8d686b42e
Create Date: 2023-02-13 19:06:48.349670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32f10b5df1e'
down_revision = '33d8d686b42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_task', sa.Column('test_type', sa.Enum('PYTHON_IO', 'PYTHON_UT', name='testtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_task', 'test_type')
    # ### end Alembic commands ###
