"""empty message

Revision ID: f400359725ab
Revises: e1b6c762bb50
Create Date: 2022-08-04 14:48:59.999147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f400359725ab'
down_revision = 'e1b6c762bb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_solution', sa.Column('check_system_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_solution', 'check_system_answer')
    # ### end Alembic commands ###
