"""add solution

Revision ID: f852c6cf629c
Revises: c4c90943ab2d
Create Date: 2021-07-02 14:18:25.499556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f852c6cf629c'
down_revision = 'c4c90943ab2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_task', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_task'], ['dbo_users_tasks.id'], name='fk_dbo_solution_dbo_users_tasks_id_user_task', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo_solution')
    # ### end Alembic commands ###
