"""update user tokens

Revision ID: fcedd6e6140f
Revises: e5bdd0d0a853
Create Date: 2021-05-21 18:51:25.560365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcedd6e6140f'
down_revision = 'e5bdd0d0a853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_user', sa.Column('refresh_token', sa.String(length=200), nullable=True))
    op.add_column('dbo_user', sa.Column('vk_access_token', sa.String(length=200), nullable=True))
    op.drop_column('dbo_user', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_user', sa.Column('access_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('dbo_user', 'vk_access_token')
    op.drop_column('dbo_user', 'refresh_token')
    # ### end Alembic commands ###
