"""course name is unique

Revision ID: fd1d27ed83ec
Revises: bf7ac7601bb9
Create Date: 2021-07-02 17:08:39.016263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1d27ed83ec'
down_revision = 'bf7ac7601bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dbo_course', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dbo_course', type_='unique')
    # ### end Alembic commands ###
